### ISSUE TITLE
System.Reflection.TargetInvocationException 

### ISSUE THREAD

**Issue by ferhattelci** [rgvlee/EntityFrameworkCore.DbContextBackedMock.Moq#1]
Hey when i use your code snippet and create the builder with
`var builder = new DbContextMockBuilder<TestContext>();` 
I'm getting the error 

> NotSupportedException: Invalid setup on a non-virtual (overridable in VB) member: <param> => <param>.

If i use the DBContextOptionsBuilder, it works fine. So is there a way to cast this? 
Thanks.

**Comment by rgvlee** [comment]
One reason this may occur is if the DbSet/DbQuery properties on your DbContext are not virtual. They must be virtual for Moq to be able to mock them.

```
public class TestContext : DbContext {
        public virtual DbSet<TestEntity1> TestEntities { get; set; }

```

If this does happen to be the issue and you don't want to make them all virtual, another option is to set the `addSetUpForAllDbSets` constructor argument to false and perform explicit set ups on the properties that need to be mocked. This will stop the builder automatically setting up the DbSet/DbQuery properties on the mock.
The DbSet/DbQuery properties that you want to mock will still need to be virtual though for the reason above.

```
var builder = new DbContextMockBuilder<TestContext>(false);
builder.AddSetUpFor(x => x.TestEntities);
var mockedContext = builder.GetMockedDbContext();
```

If none of the above is the issue, can you provide me with the full exception and if possible sample code that breaks.

**Comment by rgvlee** [comment]
With a potential solution provided and no further information available I am closing this for now. Happy to reopen if more information is/repo steps are provided.
